name: Update Language Stats

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: StefVuck/Github-Language-Stats@v1.1.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          visualization_types: "leaderboard bar donut"
          output_path: "stats"
          exclude_languages: "Markdown"
          dark_mode: "true"

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stats/ -f
          git commit -m "chore: update lang stats" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
