name: Update Language Stats

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate top langs card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=nalpsa&layout=donut&theme=tokyonight&langs_count=20&locale=pt-br
          path: stats/top-langs-donut.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate top langs compact
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=nalpsa&layout=compact&theme=tokyonight&langs_count=10&locale=pt-br
          path: stats/top-langs-compact.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add stats/
          git commit -m "chore: update lang stats" || exit 0
          git push
